create table CITIZENS
(
  BSN INTEGER primary key,
  CODE VARCHAR [255] not null,
  GENDER VARCHAR [255] not null,
  GIVEN_NAME VARCHAR [255] not null,
  SURNAME VARCHAR [255] not null,
  ADDRESS VARCHAR [255] not null,
  NATIONALITY VARCHAR [255] not null,
  IMAGE_URL VARCHAR [255] not null,
  DATE_OF_BIRTH INTEGER not null,
  PLACE_OF_BIRTH VARCHAR [255] not null,
  PASSPORT_NUMBER VARCHAR [255] not null,
  PASSPORT_DATE_OF_ISSUE INTEGER not null,
  PASSPORT_DATE_OF_EXPIRY INTEGER not null,
  PASSPORT_AUTHORITY VARCHAR [255] not null,
  GOVERNMENT_DID VARCHAR [255],
  CITIZEN_DID VARCHAR [255],
  DATE_OF_DID_ONBOARDING INTEGER
)
;