INSERT INTO CITIZENS (
  BSN,
  CODE,
  GENDER,
  GIVEN_NAME,
  SURNAME,
  ADDRESS,
  NATIONALITY,
  IMAGE_URL,
  DATE_OF_BIRTH,
  PLACE_OF_BIRTH,
  PASSPORT_NUMBER,
  PASSPORT_DATE_OF_ISSUE,
  PASSPORT_DATE_OF_EXPIRY,
  PASSPORT_AUTHORITY,
  GOVERNMENT_DID,
  CITIZEN_DID,
  DATE_OF_DID_ONBOARDING
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,null,null,null);
